version: "3.8"

services:
  mysql:
    image: mysql
    container_name: rizao-mysql
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: lqd31415926
    volumes:
      - "./mysql/conf:/etc/mysql/conf.d"
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/init:/docker-entrypoint-initdb.d"
    networks:
      - rizao-net
  rizao-jar:
    build: 
      context: .
      dockerfile: rizao_dockerfile
    container_name: rizao-jar
    ports:
      - "8080:8080"
    volumes:
      - "./nginx/html/uploads:/root/uploads"
    networks:
      - rizao-net
    depends_on:
      - mysql
  nginx:
    image: nginx
    container_name: rizao-nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/html:/usr/share/nginx/html"
    depends_on:
      - rizao-jar
    networks:
      - rizao-net
networks:
  rizao-net:
    name: rizao
